const CATALOG = [
        {
            "id": 42854,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42854\/dd1c88bb90293f223bd79027bc19dbbe3a4a06a8.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42854\/dd1c88bb90293f223bd79027bc19dbbe3a4a06a8.png",
            "stock": 42,
            "article": "BST1009",
            "name": "Блестящие детали красоты",
            "price": 390,
            "ptype": "tube1",
            "size": "40x50",
            "params": [],
            "parent": "41289",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/artofminimalism\/17374-blestyashhie-detali-krasotyi.html",
            "complexity": "2",
            "buy_price": "8.40",
            "buy_price_uah": "294.00",
            "description": "Размер 40x50 см\n                     \n                       Комплектация набору: \n                       пронумерованный холст, \n                       деревянные магнитные планки, \n                       три кисточки, \n                       акриловый лак и крепления, \n                       стикеры с музыкой, подборкой фильмов, подкастов и видео\n                        Обратите внимание, что цвета могут незначительно отличаться от показанных на фото!\n                        ",
            "category": "Коллекция Минимализм"
        },
        {
            "id": 42853,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42853\/c72143c98609ed26bf51dd1e5fdd500d86bfbfc4.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42853\/c72143c98609ed26bf51dd1e5fdd500d86bfbfc4.png",
            "stock": 44,
            "article": "BST1008",
            "name": "Нежные детали красоты",
            "price": 390,
            "ptype": "tube1",
            "size": "40x50",
            "params": [],
            "parent": "41289",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/artofminimalism\/17373-nezhnyie-detali-krasotyi.html",
            "complexity": "2",
            "buy_price": "8.40",
            "buy_price_uah": "294.00",
            "description": "Размер 40x50 см\n                     \n                       Комплектация набору: \n                       пронумерованный холст, \n                       деревянные магнитные планки, \n                       три кисточки, \n                       акриловый лак и крепления, \n                       стикеры с музыкой, подборкой фильмов, подкастов и видео\n                        Обратите внимание, что цвета могут незначительно отличаться от показанных на фото!\n                        ",
            "category": "Коллекция Минимализм"
        },
        {
            "id": 42852,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42852\/361e82d3c9e04e76ed45b2ed0408157edf594751.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42852\/361e82d3c9e04e76ed45b2ed0408157edf594751.png",
            "stock": 47,
            "article": "BST1007",
            "name": "Космические детали красоты",
            "price": 390,
            "ptype": "tube1",
            "size": "40x50",
            "params": [],
            "parent": "41289",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/artofminimalism\/17372-kosmicheskie-detali-krasotyi.html",
            "complexity": "2",
            "buy_price": "8.40",
            "buy_price_uah": "294.00",
            "description": "Размер 40x50 см\n                     \n                       Комплектация набору: \n                       пронумерованный холст, \n                       деревянные магнитные планки, \n                       три кисточки, \n                       акриловый лак и крепления, \n                       стикеры с музыкой, подборкой фильмов, подкастов и видео\n                        Обратите внимание, что цвета могут незначительно отличаться от показанных на фото!\n                        ",
            "category": "Коллекция Минимализм"
        },
        {
            "id": 42851,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42851\/9e9d0d3737a9065eb07442b99b15ba5ab7736182.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42851\/9e9d0d3737a9065eb07442b99b15ba5ab7736182.png",
            "stock": 36,
            "article": "BST1006",
            "name": "Солнце на горизонте",
            "price": 390,
            "ptype": "tube1",
            "size": "40x50",
            "params": [],
            "parent": "41289",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/artofminimalism\/17371-solncze-na-gorizonte.html",
            "complexity": "2",
            "buy_price": "8.40",
            "buy_price_uah": "294.00",
            "description": "Размер 40x50 см\n                     \n                       Комплектация набору: \n                       пронумерованный холст, \n                       деревянные магнитные планки, \n                       три кисточки, \n                       акриловый лак и крепления, \n                       стикеры с музыкой, подборкой фильмов, подкастов и видео\n                        Обратите внимание, что цвета могут незначительно отличаться от показанных на фото!\n                        ",
            "category": "Коллекция Минимализм"
        },
        {
            "id": 42850,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42850\/c51d9d58b5234a94ea0fb01b073e267e381dd8ba.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42850\/c51d9d58b5234a94ea0fb01b073e267e381dd8ba.png",
            "stock": 26,
            "article": "BST1005",
            "name": "Вдохновение",
            "price": 390,
            "ptype": "tube1",
            "size": "40x50",
            "params": [],
            "parent": "41289",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/artofminimalism\/17370-vdoxnovenie.html",
            "complexity": "2",
            "buy_price": "8.40",
            "buy_price_uah": "294.00",
            "description": "Размер 40x50 см\n                     \n                       Комплектация набору: \n                       пронумерованный холст, \n                       деревянные магнитные планки, \n                       три кисточки, \n                       акриловый лак и крепления, \n                       стикеры с музыкой, подборкой фильмов, подкастов и видео\n                        Обратите внимание, что цвета могут незначительно отличаться от показанных на фото!\n                        ",
            "category": "Коллекция Минимализм"
        },
        {
            "id": 42849,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42849\/c95dac0acf4d4e090c29c7fd93ece72a18e6bd68.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42849\/c95dac0acf4d4e090c29c7fd93ece72a18e6bd68.png",
            "stock": 37,
            "article": "BST1004",
            "name": "Время для медитации",
            "price": 390,
            "ptype": "tube1",
            "size": "40x50",
            "params": [],
            "parent": "41289",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/artofminimalism\/17369-vremya-dlya-meditaczii.html",
            "complexity": "2",
            "buy_price": "8.40",
            "buy_price_uah": "294.00",
            "description": "Размер 40x50 см\n                     \n                       Комплектация набору: \n                       пронумерованный холст, \n                       деревянные магнитные планки, \n                       три кисточки, \n                       акриловый лак и крепления, \n                       стикеры с музыкой, подборкой фильмов, подкастов и видео\n                        Обратите внимание, что цвета могут незначительно отличаться от показанных на фото!\n                        ",
            "category": "Коллекция Минимализм"
        },
        {
            "id": 42848,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42848\/831606eaa9669fa4d7f783151c9818f8d834ef42.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42848\/831606eaa9669fa4d7f783151c9818f8d834ef42.png",
            "stock": 11,
            "article": "BST1003",
            "name": "Монстера на темном фоне",
            "price": 390,
            "ptype": "tube1",
            "size": "40x50",
            "params": [],
            "parent": "41289",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/artofminimalism\/17368-monstera-na-temnom-fone.html",
            "complexity": "2",
            "buy_price": "8.40",
            "buy_price_uah": "294.00",
            "description": "Размер 40x50 см\n                     \n                       Комплектация набору: \n                       пронумерованный холст, \n                       деревянные магнитные планки, \n                       три кисточки, \n                       акриловый лак и крепления, \n                       стикеры с музыкой, подборкой фильмов, подкастов и видео\n                        Обратите внимание, что цвета могут незначительно отличаться от показанных на фото!\n                        ",
            "category": "Коллекция Минимализм"
        },
        {
            "id": 42847,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42847\/25a2c7de39cbe6deb492f5ba2030cd6eae33e2e8.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42847\/25a2c7de39cbe6deb492f5ba2030cd6eae33e2e8.png",
            "stock": 10,
            "article": "BST1002",
            "name": "Экзотическая монстера",
            "price": 390,
            "ptype": "tube1",
            "size": "40x50",
            "params": [],
            "parent": "41289",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/artofminimalism\/17367-ekzoticheskaya-monstera.html",
            "complexity": "2",
            "buy_price": "8.40",
            "buy_price_uah": "294.00",
            "description": "Размер 40x50 см\n                     \n                       Комплектация набору: \n                       пронумерованный холст, \n                       деревянные магнитные планки, \n                       три кисточки, \n                       акриловый лак и крепления, \n                       стикеры с музыкой, подборкой фильмов, подкастов и видео\n                        Обратите внимание, что цвета могут незначительно отличаться от показанных на фото!\n                        ",
            "category": "Коллекция Минимализм"
        },
        {
            "id": 43056,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43056\/9c92676c418d9f1ce47f5b560844ac6992f95270.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43056\/9c92676c418d9f1ce47f5b560844ac6992f95270.jpg",
            "stock": 2,
            "article": "BS53082",
            "name": "Кошка Защитница ©Марианна Пащук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/17821-koshka-zashhitnicza-©marianna-pashhuk.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43192,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43192\/bc2401f5002bc95dfe145e7e10d55f043b6422a0.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43192\/bc2401f5002bc95dfe145e7e10d55f043b6422a0.jpg",
            "stock": 1,
            "article": "BS53159",
            "name": "Котик Kalush ©Марианна Пащук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/18097-kotik-kalush-©marianna-pashhuk.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43453,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43453\/7aeb24f874cb4de8876d26e5606c4d6f73a956a7.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43453\/7aeb24f874cb4de8876d26e5606c4d6f73a956a7.png",
            "stock": 1,
            "article": "BS53219",
            "name": "Водоворот пионов @Дарья Михайлишина",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/21026-vodovorot-pionov-darya-mixajlishina.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43178,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43178\/53c69f4d3dd77eca41daf7ad0c07aae5a49a54a2.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43178\/53c69f4d3dd77eca41daf7ad0c07aae5a49a54a2.jpg",
            "stock": 1,
            "article": "BS53126",
            "name": "Кошка украиночка ©Марианна Пащук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/18070-koshka-ukrainochka-©marianna-pashhuk.html",
            "complexity": "5",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 41774,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41774\/d1d88aa1166607fc3b7791afa981313838e0a157.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41774\/d1d88aa1166607fc3b7791afa981313838e0a157.jpg",
            "stock": 1,
            "article": "BS52470",
            "name": "История пионов",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/14942-istoriya-pionov.html",
            "complexity": "5",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43171,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43171\/a25aca5f1c9d01b586e234f761fd9e3e5e8ab699.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43171\/a25aca5f1c9d01b586e234f761fd9e3e5e8ab699.png",
            "stock": 1,
            "article": "BS53118",
            "name": "Котик врач ©Марианна Пащук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/18063-kotik-vrach-©marianna-pashhuk.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43457,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43457\/561ba1a11e731e34885e8f03b39bfbedc92f5477.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43457\/561ba1a11e731e34885e8f03b39bfbedc92f5477.jpg",
            "stock": 3,
            "article": "BS53223",
            "name": "Цветущая кошка @marysha_art",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/21030-czvetushhaya-koshka-marysha-art.html",
            "complexity": "3",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 38287,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/38287\/21c5faba80fcf493fde49f7884be051f4aa2a6b3.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/38287\/21c5faba80fcf493fde49f7884be051f4aa2a6b3.jpg",
            "stock": 129,
            "article": "GX33799",
            "name": "Драконда",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/38287.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 40096,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/40096\/82a37414de4c781433aedc165449fc7597f61e12.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/40096\/82a37414de4c781433aedc165449fc7597f61e12.jpg",
            "stock": 10,
            "article": "GX39229",
            "name": "Неоновая кошка",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8746",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartini-po-nomeram\/pejzazhi-i-doma\/9605-neonovaya-koshka.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Поп-арт"
        },
        {
            "id": 41330,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41330\/f7b9ca3ca2a204caec8dca95e00d5c95b6b5600e.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41330\/f7b9ca3ca2a204caec8dca95e00d5c95b6b5600e.jpg",
            "stock": 39,
            "article": "BS52321",
            "name": "Горное утро",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/14387-gornoe-utro.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 41325,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41325\/179ecf982ea4b82c1b3cf0fe572db252902e1eb4.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41325\/179ecf982ea4b82c1b3cf0fe572db252902e1eb4.jpg",
            "stock": 41,
            "article": "BS40542",
            "name": "Дело в шляпе",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/14382-delo-v-shlyape.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 41131,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41131\/80ff9f0011d924e13fb51899c016163d68e48122.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41131\/80ff9f0011d924e13fb51899c016163d68e48122.jpg",
            "stock": 24,
            "article": "BS52180",
            "name": "Лазурная дорога",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8785",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartini-po-nomeram\/pejzazhi-i-doma\/14031-lazurnaya-doroga.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Природа"
        },
        {
            "id": 40378,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/40378\/6b66e81ea691afb833f08a0c9730438f375e8211.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/40378\/6b66e81ea691afb833f08a0c9730438f375e8211.jpg",
            "stock": 30,
            "article": "BS24594",
            "name": "На закате",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8785",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartini-po-nomeram\/pejzazhi-i-doma\/12153-na-zakate.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Природа"
        },
        {
            "id": 39929,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/39929\/7d80d7b4fe62b18f46220f65be220069664fb2f2.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/39929\/7d80d7b4fe62b18f46220f65be220069664fb2f2.jpg",
            "stock": 29,
            "article": "BS51375",
            "name": "Дом у озера",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8759",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartini-po-nomeram\/pejzazhi\/9241-dom-u-ozera.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Пейзажи"
        },
        {
            "id": 39602,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/39602\/36bc52419225240139ffdbc62b5406e982024a6b.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/39602\/36bc52419225240139ffdbc62b5406e982024a6b.jpg",
            "stock": 31,
            "article": "BS28734",
            "name": "Мечты в небе",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8759",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartini-po-nomeram\/pejzazhi\/8628-mechtyi-v-nebe.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Пейзажи"
        },
        {
            "id": 42751,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42751\/c30e47538a8ddcde0763001f71053366f8e3525f.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42751\/c30e47538a8ddcde0763001f71053366f8e3525f.jpg",
            "stock": 12,
            "article": "BS24302",
            "name": "Милый Тигрёнок",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/17096-milyij-tigryonok.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 41761,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41761\/57cb8a610436d3cbe2de4b9cefcbb4434bccb0fa.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41761\/57cb8a610436d3cbe2de4b9cefcbb4434bccb0fa.jpg",
            "stock": 35,
            "article": "BS52443",
            "name": "Cерая лошадка",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/14912-ceraya-loshadka.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 41690,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41690\/f4b931e33aff87c768ddd4ada087b983f3ac50c9.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41690\/f4b931e33aff87c768ddd4ada087b983f3ac50c9.jpg",
            "stock": 37,
            "article": "BS52250",
            "name": "Венеция",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8784",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/goroda\/14836-venecziya.html",
            "complexity": "2",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Города"
        },
        {
            "id": 41594,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41594\/e4093c687f23a74fc9189c9a86ecc3788cbcd1bd.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41594\/e4093c687f23a74fc9189c9a86ecc3788cbcd1bd.png",
            "stock": 38,
            "article": "BS52292",
            "name": "Взгляд на прайд",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/14720-vzglyad-na-prajd.html",
            "complexity": "2",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 41564,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41564\/33aa48530a8326059d39fb0a2a48f5ea4208982e.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41564\/33aa48530a8326059d39fb0a2a48f5ea4208982e.jpg",
            "stock": 40,
            "article": "BS52251",
            "name": "Лев в мозаике",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8746",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/pejzazhi-i-doma\/14690-lev-v-mozaike.html",
            "complexity": "1",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Поп-арт"
        },
        {
            "id": 41518,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41518\/244fa5586d3a6c40f0335c682afd3c694b707026.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41518\/244fa5586d3a6c40f0335c682afd3c694b707026.jpg",
            "stock": 42,
            "article": "BS52238",
            "name": "Космополитен",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/14644-kosmopoliten.html",
            "complexity": "1",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 41515,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41515\/184b1a966191c0f142e652fd0c19298577028f91.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41515\/184b1a966191c0f142e652fd0c19298577028f91.jpg",
            "stock": 33,
            "article": "BS52233",
            "name": "Узор слона",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/14641-uzor-slona.html",
            "complexity": "2",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 41510,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41510\/5a9fd25a388272fa427840a3fd91cb01b23d78bb.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41510\/5a9fd25a388272fa427840a3fd91cb01b23d78bb.png",
            "stock": 34,
            "article": "BS30145",
            "name": "В плаванье!",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/14636-v-plavane!.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 41508,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41508\/f55fb71eb0906a2f6d9eabbdea7aa5672ca054e7.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41508\/f55fb71eb0906a2f6d9eabbdea7aa5672ca054e7.jpg",
            "stock": 36,
            "article": "BS52230",
            "name": "Прикосновение моря",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/14633-prikosnovenie-morya.html",
            "complexity": "2",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 41503,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41503\/e1193ebcd75732279e5f4209f2059f3fd944adc2.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41503\/e1193ebcd75732279e5f4209f2059f3fd944adc2.jpg",
            "stock": 40,
            "article": "BS52227",
            "name": "Радужный Лео",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8746",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/pejzazhi-i-doma\/14627-raduzhnyij-leo.html",
            "complexity": "1",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Поп-арт"
        },
        {
            "id": 41502,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41502\/36df9c2b4366fbdf23b356a93cf285cf427ce40c.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41502\/36df9c2b4366fbdf23b356a93cf285cf427ce40c.png",
            "stock": 41,
            "article": "BS52225",
            "name": "Радужный Марли",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8746",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/pejzazhi-i-doma\/14626-raduzhnyij-marli.html",
            "complexity": "1",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Поп-арт"
        },
        {
            "id": 41464,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41464\/9376c9a5c2c2e8aa7ba7ebf78f53230ddb868056.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41464\/9376c9a5c2c2e8aa7ba7ebf78f53230ddb868056.jpg",
            "stock": 43,
            "article": "BS52454",
            "name": "Завтрак в теплых тонах",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8757",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/czvetyi\/14581-zavtrak-v-teplyix-tonax.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Цветы"
        },
        {
            "id": 43455,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43455\/91d742895db74a5075a513c80ae0ca44b86fcaca.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43455\/91d742895db74a5075a513c80ae0ca44b86fcaca.jpg",
            "stock": 87,
            "article": "BS53146",
            "name": "Цветущий герб @Svetlana Drab",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8757",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/czvetyi\/21028-czvetushhij-gerb-svetlana-drab.html",
            "complexity": "2",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Цветы"
        },
        {
            "id": 43500,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43500\/bb67c68717b42860b5769d8e80dfd3954f928bb6.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43500\/bb67c68717b42860b5769d8e80dfd3954f928bb6.jpg",
            "stock": 56,
            "article": "BS53224",
            "name": "Лапка поддержки @marysha_art",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/21111-lapka-podderzhki-marysha-art.html",
            "complexity": "3",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 39011,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/39011\/47b48470b343751f552eac81b6b28ec9d31c0280.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/39011\/47b48470b343751f552eac81b6b28ec9d31c0280.jpg",
            "stock": 2,
            "article": "GX35619",
            "name": "Кот в звездную ночь",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartini-po-nomeram\/zhivotnyie\/39011.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43309,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43309\/c91b429ec471e32c721413a9abae08c69e738bf5.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43309\/c91b429ec471e32c721413a9abae08c69e738bf5.jpg",
            "stock": 22,
            "article": "BS53173",
            "name": "Девушки из ВСУ @Матюшко Наталья",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/18217-devushki-iz-vsu-matyushko-natalya.html",
            "complexity": "2",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43310,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43310\/b8a50e42f9c387337f4a2dceac61042dfeddf91b.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43310\/b8a50e42f9c387337f4a2dceac61042dfeddf91b.jpg",
            "stock": 17,
            "article": "BS53172",
            "name": "Детская мечта @Валентина Дуван",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/18218-detskaya-mechta-valentina-duvan.html",
            "complexity": "2",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43456,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43456\/fb73cd6e3602ea6779646a45e7bab5e2c36aa7d2.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43456\/fb73cd6e3602ea6779646a45e7bab5e2c36aa7d2.jpg",
            "stock": 33,
            "article": "BS53147",
            "name": "Цветущий флаг @Светлана Драб",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8757",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/czvetyi\/21029-czvetushhij-flag-svetlana-drab.html",
            "complexity": "2",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Цветы"
        },
        {
            "id": 41602,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41602\/b0ae7fbfdb04733d90db4e91688393288dbf5705.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41602\/b0ae7fbfdb04733d90db4e91688393288dbf5705.png",
            "stock": 36,
            "article": "BS51563",
            "name": "Весенняя Венеция",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8784",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/goroda\/14728-vesennyaya-venecziya.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Города"
        },
        {
            "id": 43185,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43185\/c67657ada86ceff6bd62fbb9298f51f88eb10bdd.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43185\/c67657ada86ceff6bd62fbb9298f51f88eb10bdd.jpg",
            "stock": 24,
            "article": "BS53129",
            "name": "В надежных объятиях ©Соломия Ковальчук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/18075-v-nadezhnyix-obyatiyax.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43211,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43211\/a2dcbc9765256bdc146b35155fb3675dfe852a72.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43211\/a2dcbc9765256bdc146b35155fb3675dfe852a72.jpg",
            "stock": 11,
            "article": "BS53128",
            "name": "Нарисованний закат @Дарина Михайлишин",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/18119-narisovannij-zakat-darina-mixajlishin.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43215,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43215\/837e2776fe9da3e6fb0c61e8c0be5e570da0e3d5.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43215\/837e2776fe9da3e6fb0c61e8c0be5e570da0e3d5.jpg",
            "stock": 87,
            "article": "BS53138",
            "name": "Устойчивый Чернигов © Захарова Наталья",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/18123-ustojchivyij-chernigov-©-zaxarova-natalya.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43307,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43307\/91e163c243dac98b38f509229ae3a7816e3b1920.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43307\/91e163c243dac98b38f509229ae3a7816e3b1920.jpg",
            "stock": 81,
            "article": "BS53155",
            "name": "Маленькая украиночка @ Ольга Бородай",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/18215-malenkaya-ukrainochka-olga-borodaj.html",
            "complexity": "2",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43301,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43301\/7e9e207a5b193dd66e22d7cce0139b1b7a4ccadb.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43301\/7e9e207a5b193dd66e22d7cce0139b1b7a4ccadb.jpg",
            "stock": 41,
            "article": "BS53157",
            "name": "Зайчик из ВСУ @ Екатерина Валерьева",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/18209-zajchik-iz-vsu-ekaterina-valereva.html",
            "complexity": "2",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43308,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43308\/da90fd7247ae6d3171aa89afdb8e69517edf41e0.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43308\/da90fd7247ae6d3171aa89afdb8e69517edf41e0.png",
            "stock": 30,
            "article": "BS53158",
            "name": "В надежных руках @Елена Майхрич",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/18216-v-nadezhnyix-rukax-elena-majxrich.html",
            "complexity": "2",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 40588,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/40588\/02ca2353353d4b877bd69b21f7d6c3b50c124692.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/40588\/02ca2353353d4b877bd69b21f7d6c3b50c124692.jpg",
            "stock": 48,
            "article": "BS51481",
            "name": "Прикосновение пионов",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/12789-prikosnovenie-pionov.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43014,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43014\/b203f13395d110445e63de80f2572e029265b431.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43014\/b203f13395d110445e63de80f2572e029265b431.jpg",
            "stock": 168,
            "article": "BS53060",
            "name": "Призрак Киева ©Василик Мария",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/17690-prizrak-kieva.html",
            "complexity": "3",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43047,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43047\/ce01c50b8530db3e1b1335fe4e15d143eea17a08.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43047\/ce01c50b8530db3e1b1335fe4e15d143eea17a08.jpg",
            "stock": 49,
            "article": "BS53036",
            "name": "Весна в бокалах  © Оксана Воробей",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8757",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/czvetyi\/17805-vesna-v-bokalax-miss-maleficient.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Цветы"
        },
        {
            "id": 43090,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43090\/12911020796d8b7339bccede49aab99717ae2982.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43090\/12911020796d8b7339bccede49aab99717ae2982.jpg",
            "stock": 15,
            "article": "BS53107",
            "name": "Несокрушимый Харьков © Захарова Наталия",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/17879-xarkov.html",
            "complexity": "3",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 41858,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41858\/5cbe7d03c9d7512b78e2b5844e1c5054faf7bf6f.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/41858\/5cbe7d03c9d7512b78e2b5844e1c5054faf7bf6f.jpg",
            "stock": 35,
            "article": "BS52496",
            "name": "Добро пожаловать",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8784",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/goroda\/15053-dobro-pozhalovat.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Города"
        },
        {
            "id": 42892,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42892\/207c78ed2bcf5c675bc710492f8f16da4a5bf4c6.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42892\/207c78ed2bcf5c675bc710492f8f16da4a5bf4c6.jpg",
            "stock": 3,
            "article": "GX22684",
            "name": "Умка на севере",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/17439-umka-na-severe.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 40996,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/40996\/4592b364a55879f1ad1d6c7f12a0859ba39d8b76.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/40996\/4592b364a55879f1ad1d6c7f12a0859ba39d8b76.jpg",
            "stock": 128,
            "article": "GX5737",
            "name": "Дух леса",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartini-po-nomeram\/zhivotnyie\/13905-dux-lesa.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 42758,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42758\/4f55b4c7dfdd2ff0e503fdc54bbdc7031aa3813f.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42758\/4f55b4c7dfdd2ff0e503fdc54bbdc7031aa3813f.jpg",
            "stock": 2,
            "article": "GX41145",
            "name": "Красавец олень",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/17115-krasavecz-olen.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 42907,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42907\/673742f7f3b9939ea8a630b0bcbaae5bcbb7f7ce.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/42907\/673742f7f3b9939ea8a630b0bcbaae5bcbb7f7ce.jpg",
            "stock": 110,
            "article": "BS53031",
            "name": "Гимнастка",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/17509-gimnastka.html",
            "complexity": "3",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43076,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43076\/00c74321da6c14468b1a91f5b1ce9a2c57f1b556.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43076\/00c74321da6c14468b1a91f5b1ce9a2c57f1b556.png",
            "stock": 120,
            "article": "GX66170",
            "name": "Фламинго в цветочном арте",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/17845-flamingo-v-czvetochnom-arte.html",
            "complexity": "2",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 38334,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/38334\/5651b50eb49624ed476e3e334decea9fc61fde64.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/38334\/5651b50eb49624ed476e3e334decea9fc61fde64.jpg",
            "stock": 11,
            "article": "GX32268",
            "name": "Вечерняя площадь Венеции",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8784",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartini-po-nomeram\/gorodskie-pejzazhi-i-sooruzheniya\/38334.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Города"
        },
        {
            "id": 43038,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43038\/c19f4c7fef7e31908f350853644fdd019fc95865.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43038\/c19f4c7fef7e31908f350853644fdd019fc95865.jpg",
            "stock": 14,
            "article": "BS52836",
            "name": "Сакура в Париже",
            "price": 240,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8784",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/goroda\/17741-sakura-v-parizhe.html",
            "complexity": "4",
            "buy_price": "5.20",
            "buy_price_uah": "182.00",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Города"
        },
        {
            "id": 43218,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43218\/e431aac14d3507d62b8ce038041340d2f30ee1a3.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43218\/e431aac14d3507d62b8ce038041340d2f30ee1a3.jpg",
            "stock": 35,
            "article": "BS53099",
            "name": "Украина победит! ©Гринченко Анастасия",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/18126-ukraina-pobedit!-©grinchenko-anastasiya.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43052,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43052\/ad4b07b4225328009fb48dae1929e80aba36273e.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43052\/ad4b07b4225328009fb48dae1929e80aba36273e.jpg",
            "stock": 50,
            "article": "BS53078",
            "name": "Семейное тепло ©Svetlana Drab",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/17817-semejnoe-teplo-©svetlana-drab.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43013,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43013\/9d3e1a49892afad5c7cd19d522d6d153a188a4ca.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43013\/9d3e1a49892afad5c7cd19d522d6d153a188a4ca.jpg",
            "stock": 93,
            "article": "BS53071",
            "name": "Мы расцветем! ©Полина Скурихина",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/17689-myi-rasczvetem!.html",
            "complexity": "2",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43180,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43180\/c1acafc02be795f1169f6e9a50107089111f92fb.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43180\/c1acafc02be795f1169f6e9a50107089111f92fb.jpg",
            "stock": 159,
            "article": "BS53116",
            "name": "Котик Бетмэн ©Марианна Пащук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/18072-kotik-betmen-©marianna-pashhuk.html",
            "complexity": "3",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43179,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43179\/69c0e1ab0efc43b4254a44e8ea9d3249f7198d6b.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43179\/69c0e1ab0efc43b4254a44e8ea9d3249f7198d6b.png",
            "stock": 128,
            "article": "BS53119",
            "name": "Кошка Фрида ©Марианна Пащук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/18071-koshka-frida-©marianna-pashhuk.html",
            "complexity": "3",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43177,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43177\/205abc8f52870ed9e43fb41714f9537ec90a0b49.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43177\/205abc8f52870ed9e43fb41714f9537ec90a0b49.jpg",
            "stock": 61,
            "article": "BS53125",
            "name": "Котик с Чернобаевики ©Марианна Пащук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/18069-kotik-s-chernobaeviki-©marianna-pashhuk.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43175,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43175\/73ed281c3a369441b55f925536263c569f2bdc5b.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43175\/73ed281c3a369441b55f925536263c569f2bdc5b.jpg",
            "stock": 99,
            "article": "BS53123",
            "name": "Котик украинский Нептун ©Марианна Пащук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/18067-kotik-ukrainskij-neptun-©marianna-pashhuk.html",
            "complexity": "3",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43174,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43174\/c95543cb412d6c376614ef264c7bfe8b7274a84c.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43174\/c95543cb412d6c376614ef264c7bfe8b7274a84c.jpg",
            "stock": 82,
            "article": "BS53122",
            "name": "Котик современный Козак ©Марианна Пащук",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8758",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/zhivotnyie\/18066-kotik-sovremennyij-kozak-©marianna-pashhuk.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Животные, птицы и рыбы"
        },
        {
            "id": 43010,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43010\/40e66f3046c7dc8fd8365aad00c37e3f0521e230.jpg",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43010\/40e66f3046c7dc8fd8365aad00c37e3f0521e230.jpg",
            "stock": 90,
            "article": "BS53068",
            "name": "Сила Украины ©Полина Скурихина",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/17686-sila-ukrainyi.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
        {
            "id": 43051,
            "image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43051\/adce7444073a62cfa1057363af957e767c0811a3.png",
            "full_image": "https:\/\/img.brushme.com.ua\/assets\/images\/products\/43051\/adce7444073a62cfa1057363af957e767c0811a3.png",
            "stock": 5,
            "article": "BS53077",
            "name": "Мама Украина ©Anastasiia Kasarda",
            "price": 260,
            "ptype": "product",
            "size": "40x50",
            "params": [],
            "parent": "8787",
            "link": "https:\/\/brushme.com.ua\/catalog\/kartiny-po-nomeram\/lyudi-na-kartinax\/17816-nenka-ukraiina-©guminska-diana.html",
            "complexity": "4",
            "buy_price": "5.46",
            "buy_price_uah": "191.10",
            "description": "Размер 40x50 см\n                    \n                        Комплектация набора:\n                        холст на основе хлопка натянутый на деревянный подрамник с нанесенной пронумерованной схемой будущей картины\n                        3 кисти разной толщины\n                        акриловые пронумерованные краски\n                        крепления к стене для готовой картины\n                        ",
            "category": "Люди на картинах"
        },
	]
